# Generated by Django 5.1.6 on 2026-03-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_personalinfo_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplicationinfo',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Features'),
        ),
    ]
