# Generated by Django 6.0.6 on 2026-06-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_webapplicationinfo_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplicationinfo',
            name='website',
            field=models.TextField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
